#!/bin/sh

log() {
    echo "mender:$*" >&2
}

log "$(mender -show-artifact): $(basename "$0") was called!"

psplash-write "MSG Installation is now complete"
psplash-write "PROGRESS 75"
systemctl restart boot-script
exit 0
