#!/bin/sh

log() {
    echo "mender:$*" >&2
}

log "$(mender -show-artifact): $(basename "$0") was called!"

psplash-write "MSG Something goes wrong, Rollback is needed !"
psplash-write "PROGRESS 100"
systemctl restart boot-script
exit 0
